/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx}',
    './src/components/**/*.{js,ts,jsx,tsx}',
    './src/contexts/**/*.{js,ts,jsx,tsx}',
    './src/app/**/*.{js,ts,jsx,tsx}',
    './src/providers/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        background: 'rgb(var(--background) / <alpha-value>)',
        foreground: 'rgba(var(--foreground) / <alpha-value>)',
        card: 'rgba(var(--card) / <alpha-value>)',
        'card-foreground': 'rgba(var(--card-foreground) / <alpha-value>)',
        popover: 'rgba(var(--popover) / <alpha-value>)',
        'popover-foreground': 'rgba(var(--popover-foreground) / <alpha-value>)',
        primary: 'rgba(var(--primary) / <alpha-value>)',
        'primary-foreground': 'rgba(var(--primary-foreground) / <alpha-value>)',
        'primary-accent': 'rgba(var(--primary-accent) / <alpha-value>)',
        secondary: 'rgba(var(--secondary) / <alpha-value>)',
        'secondary-foreground': 'rgba(var(--secondary-foreground) / <alpha-value>)',
        'secondary-accent': 'rgba(var(--secondary-accent) / <alpha-value>)',
        muted: 'rgba(var(--muted) / <alpha-value>)',
        'muted-foreground': 'rgba(var(--muted-foreground) / <alpha-value>)',
        accent: 'rgba(var(--accent) / <alpha-value>)',
        'accent-foreground': 'rgba(var(--accent-foreground) / <alpha-value>)',
        success: 'rgba(var(--success) / <alpha-value>)',
        'success-foreground': 'rgba(var(--success-foreground) / <alpha-value>)',
        warning: 'rgba(var(--warning) / <alpha-value>)',
        'warning-foreground': 'rgba(var(--warning-foreground) / <alpha-value>)',
        destructive: 'rgba(var(--destructive) / <alpha-value>)',
        'destructive-foreground': 'rgba(var(--destructive-foreground) / <alpha-value>)',
        border: 'rgba(var(--border) / <alpha-value>)',
        input: 'rgba(var(--input) / <alpha-value>)',

        // ── SpaceBot terminal colors ──
        terminal: {
          bg: '#0C0C0C',
          text:   '#1877F2',
          accent: '#00D9D9',
          warning: '#E6E300',
          error: '#E20000',
          dim: '#767676',
          success:   '#1877F2',
          border: '#333333',
        },
        // SpaceBot theme tokens (CSS variable mapped)
        sb: {
          'bg-primary': 'var(--sb-bg-primary)',
          'bg-secondary': 'var(--sb-bg-secondary)',
          'bg-tertiary': 'var(--sb-bg-tertiary)',
          'bg-elevated': 'var(--sb-bg-elevated)',
          'text-primary': 'var(--sb-text-primary)',
          'text-secondary': 'var(--sb-text-secondary)',
          'text-tertiary': 'var(--sb-text-tertiary)',
          'accent-lightest': 'var(--sb-accent-lightest)',
          'accent-light': 'var(--sb-accent-light)',
          accent: 'var(--sb-accent)',
          'accent-dark': 'var(--sb-accent-dark)',
          'accent-darkest': 'var(--sb-accent-darkest)',
          'border-primary': 'var(--sb-border-primary)',
          'border-secondary': 'var(--sb-border-secondary)',
          'status-online': 'var(--sb-status-online)',
          'status-error': 'var(--sb-status-error)',
          'status-warning': 'var(--sb-status-warning)',
          'status-info': 'var(--sb-status-info)',
          'link-color': 'var(--sb-link-color)',
          'link-hover': 'var(--sb-link-hover)',
          'link-visited': 'var(--sb-link-visited)',
          'nav-bg': 'var(--sb-nav-bg)',
          'nav-text': 'var(--sb-nav-text)',
          'nav-hover': 'var(--sb-nav-hover)',
          'nav-border': 'var(--sb-nav-border)',
          'caret-color': 'var(--sb-caret-color)',
          'selection-bg': 'var(--sb-selection-bg)',
          'selection-text': 'var(--sb-selection-text)',
          'scrollbar-thumb': 'var(--sb-scrollbar-thumb)',
          'scrollbar-hover': 'var(--sb-scrollbar-hover)',
        },
        human: {
          bg: '#0C0C0C',
          text: '#CCCCCC',
          accent:   '#1877F2',
          'accent-hover': '#00AA2A',
          border: '#333333',
          muted: '#666666',
          surface: '#141414',
          link: '#00D9D9',
          'link-hover': '#009FBF',
          error: '#E20000',
          warning: '#E6E300',
          ai: '#BF5FFF',
          emphasis: '#FFFFFF',
          input: '#1A1A1A',
          card: '#141414',
        },
      },
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-conic': 'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
      },
      fontFamily: {
        mono: ['var(--font-terminal)', 'JetBrains Mono', 'Fira Code', 'Source Code Pro', 'Cascadia Code', 'Consolas', 'Courier New', 'monospace'],
        display: ['var(--font-display)', '"Press Start 2P"', 'VT323', '"Share Tech Mono"', 'monospace'],
      },
      animation: {
        blink: 'blink 1s step-end infinite',
        scanline: 'scanline 8s linear infinite',
        bootUp: 'bootUp 0.5s ease-out forwards',
        blockPlace: 'blockPlace 0.15s steps(3) forwards',
        glowPulse: 'glowPulse 2s ease-in-out infinite',
        heartbeatPulse: 'heartbeatPulse 2s ease-out infinite',
        heartbeatDot: 'heartbeatDot 1.5s ease-in-out infinite',
        tickerScroll: 'tickerScroll 30s linear infinite',
        fadeSlideUp: 'fadeSlideUp 0.3s ease-out',
        glowIntensify: 'glowIntensify 0.5s ease-out',
      },
      keyframes: {
        blink: {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0' },
        },
        scanline: {
          '0%': { transform: 'translateY(-100%)' },
          '100%': { transform: 'translateY(100vh)' },
        },
        bootUp: {
          '0%': { opacity: '0', transform: 'translateY(10px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        blockPlace: {
          '0%': { opacity: '0', transform: 'scale(0.95)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        glowPulse: {
          '0%, 100%': { boxShadow: '0 0 5px #1877F233' },
          '50%': { boxShadow: '0 0 15px #1877F266' },
        },
        heartbeatPulse: {
          '0%': { boxShadow: '0 0 0 0 rgba(var(--pulse-rgb, 0, 220, 0), 0.5)' },
          '70%': { boxShadow: '0 0 0 14px rgba(var(--pulse-rgb, 0, 220, 0), 0)' },
          '100%': { boxShadow: '0 0 0 0 rgba(var(--pulse-rgb, 0, 220, 0), 0)' },
        },
        heartbeatDot: {
          '0%, 100%': { transform: 'scale(1)', opacity: '1' },
          '50%': { transform: 'scale(1.4)', opacity: '0.7' },
        },
        tickerScroll: {
          '0%': { transform: 'translateX(0)' },
          '100%': { transform: 'translateX(-50%)' },
        },
        fadeSlideUp: {
          from: { opacity: '0', transform: 'translateY(8px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        glowIntensify: {
          '0%': { boxShadow: '0 0 5px #1877F233' },
          '50%': { boxShadow: '0 0 20px #1877F266' },
          '100%': { boxShadow: '0 0 5px #1877F233' },
        },
      },
    },
  },
  darkMode: 'class',
  plugins: [],
};
