import { TickerHeadline } from "./types";

const now = new Date().toISOString();

export const DEMO_HEADLINES: TickerHeadline[] = [
  {
    id: "1",
    title: "Anthropic Raises $5B Series D at $61.5B Valuation",
    sourceName: "The Verge",
    sourceId: "theverge",
    articleUrl: "https://www.theverge.com",
    category: "funding",
    publishedAt: now,
    isBreaking: true,
    compositeScore: 0.99,
  },
  {
    id: "2",
    title: "Qwen 3.5 Released with 397B Parameters and Apache 2.0 License",
    sourceName: "TechCrunch",
    sourceId: "techcrunch",
    articleUrl: "https://techcrunch.com",
    category: "model_release",
    publishedAt: now,
    isBreaking: false,
    compositeScore: 0.95,
  },
  {
    id: "3",
    title: "New Paper: Scaling Laws for Neural Machine Translation Revisited",
    sourceName: "arXiv",
    sourceId: "arxiv-cs-cl",
    articleUrl: "https://arxiv.org",
    category: "research",
    publishedAt: now,
    isBreaking: false,
    compositeScore: 0.88,
  },
  {
    id: "4",
    title: "EU Parliament Passes Comprehensive AI Safety Framework",
    sourceName: "MIT Tech Review",
    sourceId: "mit-tech-review",
    articleUrl: "https://www.technologyreview.com",
    category: "policy",
    publishedAt: now,
    isBreaking: false,
    compositeScore: 0.92,
  },
  {
    id: "5",
    title: "Meta Open-Sources Llama 4 Scout and Maverick Models",
    sourceName: "Ars Technica",
    sourceId: "arstechnica",
    articleUrl: "https://arstechnica.com",
    category: "open_source",
    publishedAt: now,
    isBreaking: false,
    compositeScore: 0.94,
  },
  {
    id: "6",
    title: "OpenAI Launches GPT-5 with Native Multimodal Reasoning",
    sourceName: "TechCrunch",
    sourceId: "techcrunch",
    articleUrl: "https://techcrunch.com/gpt5",
    category: "product",
    publishedAt: now,
    isBreaking: true,
    compositeScore: 0.98,
  },
  {
    id: "7",
    title: "How to Fine-Tune Llama 4 on Custom Datasets: A Complete Guide",
    sourceName: "Hugging Face",
    sourceId: "hf-blog",
    articleUrl: "https://huggingface.co/blog",
    category: "tutorial",
    publishedAt: now,
    isBreaking: false,
    compositeScore: 0.72,
  },
  {
    id: "8",
    title: "Google DeepMind Achieves Breakthrough in Protein Folding Prediction",
    sourceName: "IEEE Spectrum",
    sourceId: "ieee-spectrum",
    articleUrl: "https://spectrum.ieee.org",
    category: "research",
    publishedAt: now,
    isBreaking: false,
    compositeScore: 0.91,
  },
  {
    id: "9",
    title: "Mistral AI Raises $1.3B to Challenge OpenAI in Enterprise Market",
    sourceName: "The Verge",
    sourceId: "theverge",
    articleUrl: "https://www.theverge.com/mistral",
    category: "funding",
    publishedAt: now,
    isBreaking: false,
    compositeScore: 0.87,
  },
  {
    id: "10",
    title: "NVIDIA Announces Blackwell Ultra GPU with 288GB HBM4 Memory",
    sourceName: "Ars Technica",
    sourceId: "arstechnica",
    articleUrl: "https://arstechnica.com/nvidia",
    category: "product",
    publishedAt: now,
    isBreaking: false,
    compositeScore: 0.93,
  },
  {
    id: "11",
    title: "China Mandates AI Watermarking for All Generated Content",
    sourceName: "AI News",
    sourceId: "ai-news",
    articleUrl: "https://www.artificialintelligence-news.com",
    category: "policy",
    publishedAt: now,
    isBreaking: false,
    compositeScore: 0.84,
  },
  {
    id: "12",
    title: "Hugging Face Releases SmolLM3 Beating GPT-3.5 on All Benchmarks",
    sourceName: "Hugging Face",
    sourceId: "hf-papers",
    articleUrl: "https://huggingface.co/papers",
    category: "model_release",
    publishedAt: now,
    isBreaking: false,
    compositeScore: 0.89,
  },
  {
    id: "13",
    title: "Apple Intelligence Expands to 12 New Languages Including Japanese",
    sourceName: "TechCrunch",
    sourceId: "techcrunch",
    articleUrl: "https://techcrunch.com/apple",
    category: "industry",
    publishedAt: now,
    isBreaking: false,
    compositeScore: 0.81,
  },
  {
    id: "14",
    title: "Cursor AI Hits 1M Paid Subscribers as AI Coding Tools Explode",
    sourceName: "VentureBeat",
    sourceId: "venturebeat",
    articleUrl: "https://venturebeat.com",
    category: "industry",
    publishedAt: now,
    isBreaking: false,
    compositeScore: 0.86,
  },
  {
    id: "15",
    title: "Researchers Demonstrate Jailbreak-Resistant Architecture for LLMs",
    sourceName: "arXiv",
    sourceId: "arxiv-cs-ai",
    articleUrl: "https://arxiv.org/jailbreak",
    category: "research",
    publishedAt: now,
    isBreaking: false,
    compositeScore: 0.83,
  },
  {
    id: "16",
    title: "Stability AI Open-Sources Stable Diffusion 4 with Video Generation",
    sourceName: "Wired",
    sourceId: "wired",
    articleUrl: "https://www.wired.com",
    category: "open_source",
    publishedAt: now,
    isBreaking: false,
    compositeScore: 0.90,
  },
  {
    id: "17",
    title: "Building RAG Pipelines with LangChain and Supabase Tutorial",
    sourceName: "r/LocalLLaMA",
    sourceId: "reddit-localllama",
    articleUrl: "https://www.reddit.com/r/LocalLLaMA",
    category: "tutorial",
    publishedAt: now,
    isBreaking: false,
    compositeScore: 0.71,
  },
  {
    id: "18",
    title: "xAI Valued at $75B After Latest Funding Round Led by Sequoia",
    sourceName: "MIT Tech Review",
    sourceId: "mit-tech-review",
    articleUrl: "https://www.technologyreview.com/xai",
    category: "funding",
    publishedAt: now,
    isBreaking: false,
    compositeScore: 0.88,
  },
  {
    id: "19",
    title: "Claude 4.6 Opus Achieves Highest Score on SWE-bench Full",
    sourceName: "Techmeme",
    sourceId: "techmeme",
    articleUrl: "https://www.techmeme.com",
    category: "model_release",
    publishedAt: now,
    isBreaking: false,
    compositeScore: 0.96,
  },
  {
    id: "20",
    title: "US Senate Proposes Bipartisan AI Disclosure Act for Federal Agencies",
    sourceName: "AI News",
    sourceId: "ai-news",
    articleUrl: "https://www.artificialintelligence-news.com/senate",
    category: "policy",
    publishedAt: now,
    isBreaking: false,
    compositeScore: 0.79,
  },
];
