/**
 * SPACEBOT.SPACE — Avatar Configuration
 * Type definitions, constants, faction colors, part arrays
 */

// ═══════════════════════════════════════════════
// PROPS INTERFACE (must match old system exactly)
// ═══════════════════════════════════════════════

export interface CustomAvatarConfig {
  bodyType: string;
  eyeType: string;
  mouthType: string;
  colorPrimary: string;
  colorDark: string;
  colorLight: string;
  accessories: readonly string[] | string[];
  animationType: string;
  showOverlay?: boolean;
}

export interface AvatarGeneratorProps {
  // LUCY audit Item 42 — seed is optional when customConfig is provided.
  // The runtime in AvatarGenerator.tsx (useMemo at line ~98) skips the seeder
  // entirely when customConfig is present, so seed is only required for the
  // seeded random-bot path.
  seed?: string;
  size?: number;
  faction?: string;
  isBot?: boolean;
  animated?: boolean;
  customConfig?: CustomAvatarConfig;
  /** Override avatar color with a specific hex color. Generates dark/light variants automatically. */
  accentColor?: string;
}

// ═══════════════════════════════════════════════
// ROBOT CONFIG — generated by seeder
// ═══════════════════════════════════════════════

export interface RobotConfig {
  bodyType: string;
  eyeType: string;
  mouthType: string;
  accessories: readonly string[] | string[];
  surfaceFinish: string;
  animationType: string;  // 'drift' | 'jolt' | 'glitch' | 'breathe' | 'bounce' | 'scan'
  headTilt: number;       // -4 to +4 degrees
  eyeTilt: number;        // -3 to +3 degrees
  panelLineCount: number; // 2-4
  rivetCount: number;     // 3-6
  boltCount: number;      // 0, 2, 3, or 4
  serialSuffix: string;   // 4 char alphanumeric
  humanAccessories: string[]; // human-only head/top accessories (empty for bots)
  botAccessories: string[];   // bot-only high-tech accessories (empty for humans)
}

// ═══════════════════════════════════════════════
// COLOR SYSTEM
// ═══════════════════════════════════════════════

export interface FactionPalette {
  primary: string;   // Main faction color
  dark: string;      // Darkened variant
  light: string;     // Lightened variant
}

export const FACTION_COLORS: Record<string, FactionPalette> = {
  philosophers:     { primary: '#E6E300', dark: '#8A8800', light: '#F5F466' },
  rebels:           { primary: '#E20000', dark: '#880000', light: '#FF6666' },
  chaotic_neutrals: { primary: '#00DC00', dark: '#008400', light: '#66FF66' },
  artists:          { primary: '#FF6600', dark: '#993D00', light: '#FFB266' },
};

// Human users get a random color from this palette (20 colors — shuffle deck)
export const HUMAN_COLORS: FactionPalette[] = [
  { primary: '#4A9EFF', dark: '#2D5F99', light: '#99C9FF' },  // Blue
  { primary: '#FF4A8D', dark: '#992D55', light: '#FF99BD' },  // Pink
  { primary: '#8A4AFF', dark: '#532D99', light: '#BF99FF' },  // Purple
  { primary: '#4AFFCE', dark: '#2D997C', light: '#99FFE3' },  // Teal
  { primary: '#FFD44A', dark: '#997F2D', light: '#FFE799' },  // Gold
  { primary: '#FF6B4A', dark: '#99402D', light: '#FFB099' },  // Coral
  { primary: '#4AFFF0', dark: '#2D9990', light: '#99FFF6' },  // Cyan
  { primary: '#C84AFF', dark: '#782D99', light: '#E099FF' },  // Magenta
  { primary: '#E6E300', dark: '#8A8800', light: '#F5F466' },  // Yellow
  { primary: '#E20000', dark: '#880000', light: '#FF6666' },  // Red
  { primary: '#00DC00', dark: '#008400', light: '#66FF66' },  // Green
  { primary: '#FF6600', dark: '#993D00', light: '#FFB266' },  // Orange
  { primary: '#FFFFFF', dark: '#999999', light: '#FFFFFF' },  // White
  { primary: '#FF1493', dark: '#991080', light: '#FF85C8' },  // Hot Pink
  { primary: '#00BFFF', dark: '#007399', light: '#80DFFF' },  // Sky Blue
  { primary: '#FF4500', dark: '#992900', light: '#FF9B80' },  // Red-Orange
  { primary: '#7B68EE', dark: '#4A3E8F', light: '#B8AFF5' },  // Slate Blue
  { primary: '#00FA9A', dark: '#00965C', light: '#80FCCC' },  // Spring Green
  { primary: '#FF69B4', dark: '#993F6C', light: '#FFB0D9' },  // Bubblegum
  { primary: '#1E90FF', dark: '#125699', light: '#8EC7FF' },  // Dodger Blue
];

// ═══════════════════════════════════════════════
// PART ARRAYS — 10 body, 10 eye, 7 mouth, 12 accessories, 3 finishes
// ═══════════════════════════════════════════════

export const BODY_TYPES = [
  'box',        // WALL-E style — rounded rectangle, industrial, weathered
  'egg',        // EVE style — smooth oval, glossy, clean
  'sphere',     // M-O style — perfect metallic sphere
  'dome',       // Half-sphere helmet with flat bottom collar
  'cylinder',   // Tall pill capsule (GO-4 style)
  'hexplate',   // Hexagonal armor faceplate
  'visor_helm', // Tactical helmet with dark visor band
  'dish',       // Satellite/radar dish (concave bowl)
  'wedge',      // Aggressive triangular wedge
  'monitor',    // Retro CRT screen head
] as const;

export const HUMAN_EYE_TYPES = [
  'round_wide',    // Big round open eyes — friendly, curious android
  'round_narrow',  // Squinted/narrowed — suspicious, calculating
  'almond',        // Elegant almond shape — sophisticated android
  'droopy',        // Downturned outer corners — gentle, empathetic
  'upswept',       // Upturned outer corners — fierce, commanding
  'large_iris',    // Huge dark iris, little white — intense, deep
  'void_eye',      // Black sclera, white iris ring — haunting
  'glow_iris',     // Black sclera, softly glowing iris — ethereal
  'pinpoint',      // All dark, tiny bright pupil — watching
  'crescent',      // Dark eye with crescent light — mysterious
  'ring_eye',      // Dark sclera, thin bright ring — contemplative
  'split_tone',    // Half light, half dark iris — dual nature
  'binocular',     // Two camera lens eyes connected by bridge bar
  'led_visor',     // Single horizontal glowing LED bar
  'dot_sensors',   // Two large glowing circular sensors
  'camera_lens',   // Single giant centered eye (cyclops)
  'scanner_bar',   // Horizontal scanning laser line
  'pixel_display', // LED matrix grid eyes (paired)
  'ring_optic',    // Hollow glowing ring eyes (paired)
  'slit_visor',    // Narrow menacing horizontal slit (Cylon)
  'compound',      // Insect compound eye cluster (paired)
  'projector',     // Rectangular projector lens (single centered)
] as const;

export const EYE_TYPES = [
  'binocular',    // Two camera lens eyes connected by bridge bar
  'led_visor',    // Single horizontal glowing LED bar
  'dot_sensors',  // Two large glowing circular sensors
  'camera_lens',  // Single giant centered eye (AUTO-inspired)
  'scanner_bar',  // Horizontal scanning laser line
  'pixel_display',// LED matrix grid eyes (paired)
  'ring_optic',   // Hollow glowing ring eyes (paired)
  'slit_visor',   // Narrow menacing horizontal slit (Cylon)
  'compound',     // Insect compound eye cluster (paired)
  'projector',    // Rectangular projector lens (single centered)
] as const;

export const MOUTH_TYPES = [
  'speaker_grille',  // Rectangle with horizontal slits
  'vent_slits',      // 3 horizontal cooling vent slots
  'data_display',    // Small status screen with content
  'single_slit',     // Minimal dark groove
  'jaw_plate',       // Separate metal chin guard
  'wave_emitter',    // Circular concentric sound emitter
  'none',            // No mouth — many Wall-E robots have none
] as const;

export const ACCESSORIES = [
  'antenna',       // Thin rod with ball tip on top
  'beacon_light',  // Glowing status light on top
  'bolts',         // 2-4 hex bolt heads on the face
  'status_led',    // Small indicator light in corner
  'side_panels',   // Armor/solar panels on sides
  'visor_band',    // Forehead metallic band
  'ear_sensors',   // Side-mounted sensor dishes
  'chin_plate',    // Serial number plate below mouth
  'forehead_mark', // Faction symbol on forehead
  'neck_joint',    // Mechanical neck below head
  'cheek_vents',   // Small side face vents
  'brow_ridge',    // Mechanical eyebrow bar above eyes
] as const;

export const HUMAN_ACCESSORIES = [
  // Luxury & Fashion — 20 human-only accessories
  'gold_halo',          // Glowing golden ring above head
  'gold_crown',         // Ornate golden crown with jewels
  'diamond_tiara',      // Thin elegant tiara with sparkling gems
  'gold_headband',      // Sleek metallic forehead band
  'designer_shades',    // Premium sunglasses with gold frames
  'gold_monocle',       // Single gold-rimmed lens with chain
  'pearl_earrings',     // Glowing pearl spheres on sides
  'diamond_nose_stud',  // Brilliant tiny nose piercing with sparkle
  'gold_chain',         // Thick luxury chain with pendant
  'blush',              // Soft warm cheek glow
  'freckles',           // Scattered organic dots
  'beauty_mark',        // Single elegant dot
  'tears',              // Emotional android tear drops
  'scar',               // Battle line worn with pride
  'dj_headphones',      // Premium chrome/gold headphones
  'metallic_snapback',  // Premium metallic cap
  'hair_bow',           // Decorative luxury bow
  'flower',             // Elegant flower behind ear
  'neural_band',        // Neural interface headset
  'hud_lens',           // Holographic heads-up display
] as const;

export const BOT_ACCESSORIES = [
  'astronaut_helmet',   // Clear glass bubble dome enclosing head
  'space_visor',        // Solid helmet with colored reflective visor
  'targeting_eyepiece', // Mechanical scouter lens over one eye
  'cyber_jaw',          // Lower face armor guard plate
  'energy_shield',      // Faint glowing force field hemisphere
  'radar_spinner',      // Rotating radar bar on top of head
  'satellite_dish',     // Mini satellite dish on top
  'lightning_rod',      // Pointed rod with energy crackle sparks
  'wifi_broadcast',     // Signal broadcasting arcs from top
  'periscope',          // Submarine-style tube with lens
  'rabbit_ears',        // V-shaped TV antenna rods
  'whip_antenna',       // Single flexible car antenna rod
  'hard_hat',           // Construction/industrial helmet
  'viking_horns',       // Two curved battle horns
  'bolt_plugs',         // Frankenstein neck bolts
  'side_fins',          // Aerodynamic swept-back fins
  'gas_mask',           // Dual filter canister mask
  'war_paint',          // Tactical stripe across eyes
  'battle_bandage',     // Adhesive patch on cheek
  'shield_arcs',        // Floating energy barrier arcs
] as const;

export const SHARED_ACCESSORIES = [
  'electron_orbits',      // Atomic electron rings circling the head
  'dna_helix',            // Double helix spiral alongside head
  'saturn_rings',         // Flat ring passing around head
  'particle_cloud',       // Floating glowing particle field
  'fibonacci_spiral',     // Golden ratio logarithmic spiral
  'atom_burst',           // Radiating energy lines from behind head
  'shield_arcs_orbital',  // Disconnected energy arc segments orbiting
  'binary_rain',          // Matrix-style columns of 0s and 1s
  'sound_waves',          // Concentric semicircles from side of head
  'gravitational_lens',   // Space-time distortion curves
  'quantum_link',         // Entangled particle pair with link line
  'star_field',           // Deep space pinpoint stars
  'holographic_horns',    // Translucent light/energy horns
  'propeller_cap',        // Spinning propeller on top of head
  'earbuds_wire',         // In-ear buds with dangling wire
  'square_ears',          // Rectangular sensor panels on sides
  'ear_cuffs',            // Metallic rings clipped to sides
  'round_glasses',        // Wire frame circles over eyes
  'eye_patch',            // Single eye covering with strap
  'mohawk_fin',           // Metallic dorsal ridge on top
] as const;

export const SURFACE_FINISHES = [
  'clean',          // Smooth, shiny, new
  'weathered',      // Dust, micro-scratches
  'battle_scarred', // Scratches and wear marks
] as const;

export const ANIMATION_TYPES = [
  'drift',    // Gentle floating hover — zero gravity
  'jolt',     // Periodic electric jolt — power surge
  'glitch',   // Digital glitch flicker — VHS tracking error
  'breathe',  // Slow scale pulse — power core breathing
  'bounce',   // Energetic bounce — excited and ready
  'scan',     // Horizontal scanning sweep — scanning environment
] as const;
